version: "3.8"

services:
  postgres:
    container_name: task-postgres
    image: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: techtask
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    container_name: techtask-app
#    build: .
    image: taskapp
    environment:
      DATABASE_DOMAIN: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: techtask
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      - postgres
